### ISSUE TITLE
The `app.html` page is blank after loading into Chrome

### ISSUE THREAD

**Issue by HunDunDM** [TigerHix/Bitter#5]
I have no experience developing Chrome plugins and after trying the steps below, I get a blank page.
Maybe I'm missing some steps(e.g. login), or I'm opening the plugin in the wrong way. I want to learn it, can I get any advice?

# ENV

* system: macOS v12.3.1
* node: v16.14.2
* yarn: v1.22.15
* Chrome: v101.0.4951.54

# STEP

* `git clone git@github.com:TigerHix/Bitter.git`
* `yarn && yarn build`
* Enable `Developer mode` on Chrome's `Extensions` page
* Load the `dist` folder generated by `yarn` with `Load unpacked`, then enable the plugin.
* Open `chrome-extension://<plugin_id>/app.html`, got 

<img width="745" alt="image" src="https://user-images.githubusercontent.com/19789302/167267291-f4210a0d-82aa-4379-87b1-0d833e1db83b.png">

* Click the plugin icon, got

<img width="103" alt="image" src="https://user-images.githubusercontent.com/19789302/167267763-14179751-e037-4f2c-9dd5-e4ab85f5d813.png">

**Comment by TigerHix** [comment]
Hmm, can you attach the `dist` folder as a .zip and upload it here? Upon clicking the plugin icon [it should bring you to `app.html`](https://github.com/TigerHix/Bitter/blob/master/src/entry/background.ts). I have never seen that "Hello popup" text anywhere in the code.

**Comment by HunDunDM** [comment]
Seems a bit magical, I rebuilt it and got the same result. Maybe it should be [this line of code](https://github.com/TigerHix/Bitter/blob/548bd44a0571f324f6b67ea992490e77a7958f9f/src/view/popup.vue#L3).

[dist.zip](https://github.com/TigerHix/Bitter/files/8646082/dist.zip)

**Comment by TigerHix** [comment]
> Seems a bit magical, I rebuilt it and got the same result. Maybe it should be [this line of code](https://github.com/TigerHix/Bitter/blob/548bd44a0571f324f6b67ea992490e77a7958f9f/src/view/popup.vue#L3).
> 
> [dist.zip](https://github.com/TigerHix/Bitter/files/8646082/dist.zip)

Oh got it, I forgot to modify the production manifest. `yarn build` builds the production version which uses [this manifest](https://github.com/TigerHix/Bitter/blob/01ce1f49ce7c32d38f48a8fa035d4557691d4825/src/manifest.production.json) and `yarn build-watch` (which is what I use for development because it automatically rebuilds on code change) uses [this manifest](https://github.com/TigerHix/Bitter/blob/01ce1f49ce7c32d38f48a8fa035d4557691d4825/src/manifest.development.json).

**Comment by HunDunDM** [comment]
Oh, I opened it successfully. Thanks!

<img width="585" alt="image" src="https://user-images.githubusercontent.com/19789302/167275499-1965de4f-4ad7-4062-8a21-2ce72d12c9c2.png">

**Comment by TigerHix** [comment]
Fixed by 3b5d54075794064facb3f008f5540ee33c97072f.
